package(default_visibility = ["//visibility:public"])

constraint_setting(
    name = "standard",
)

constraint_value(
    name = "14",
    constraint_setting = ":standard",
)

constraint_value(
    name = "17",
    constraint_setting = ":standard",
)

constraint_value(
    name = "20",
    constraint_setting = ":standard",
)

constraint_setting(
    name = "implementation",
)

constraint_value(
    name = "hosted",
    constraint_setting = ":implementation",
)

constraint_value(
    name = "freestanding",
    constraint_setting = ":implementation",
)
